use atw80db;

INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('112233', 'Incense Sticks', '100 pcs. of Freshly made incense sticks ', 'Brazil', '100pcIncenseSticks.jpg', 5.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('445566', 'Distressed Wood Desk in teal and shades of green', 'This artisan created desk is finished with layers of green and teal paint and then sanded to a smooth finish to show rustic and colorful layers.', 'New Zealand', 'blueDesk.jpg', 199.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('778899', 'Bud Vases- Set of 2', 'These bud vases are great as a pair, but will look equally beautiful split up in different places around your home. Perfect for displaying those wildflower buds found on lazy weekend walks!', 'Brazil', 'budVase.jpg', 16.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('123123', 'Rustic Coat Rack', 'Each coat is deeply steeped in the history of NewZealand', 'New Zealand', 'coatRack.jpg', 10.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('234234', 'Farmhouse Wall Clock', 'This totally hand made wall clock is created from plywood lumber that is cut into strips, stained, then painted with a dry-brush old white finish.', 'Brazil', 'farmhouseClock.jpg', 40.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('345345', '8oz Sandalwood Soy Candle', 'Bring the outdoors inside with our Sandalwood scented candle. This 100% Natural Soy candle has a perfect accompaniment to a good book on a cold evening.', 'Brazil', 'giftCandle.jpg', 3.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('456456', 'Wood Floating Shelves', 'Shelves are made out of PINE & MAPLE PLYWOOD, PREMIUM PINE STUD. ', 'Brazil', 'woodShelves.jpg', 39.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('567567', 'Farmhouse Distressed Frame', 'Our Farmhouse distressed picture frames are hand painted and stacked for extra depth.', 'New Zealand', 'woodPictureFrame.jpg', 6.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('678678', 'Mudcloth Pillow Cover, African Mud Cloth | Cream and Black | Asha', 'Front: Authentic African Mud Cloth Backing: Natural/Cream Cotton ', 'Angola', 'whitePillow.jpg', 10.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('789789', 'Welcome Sign, Front Door', 'Welcome your guests with this rustic Welcome Sign! We have 2 sizes available! The large sign Measures 13-3/4" wide by 72" high (6 ft) and is sure to draw attention. It measures 7” wide by 48” tall.', 'New Zealand', 'welcomeSign.jpg', 10.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('134135', 'Industrial Towel Rack Ring', 'Towel Bar Ring Small hand towel Measures 6" wide x 7" tall x 3" deep. Made with metal pipe. Finished in a lacquer. Comes with all mounting Hardware', 'New Zealand', 'towelRackRing.jpg', 17.99);
INSERT INTO products (sku, product_name, product_desc, country, product_image, price) VALUES ('264862', 'Red Pillow', 'Big red pillow to serve all your big red pillow needs.', 'Brazil', 'redPillow.jpg', 10.99);


select * from products;
